name: Continuous Integration

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
      
    - name: Generate code coverage report
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.26
      with:
        reports: '**/coverage.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline;Cobertura'
        
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v3
      with:
        name: CoverageReport
        path: coveragereport
        
    - name: Upload test results artifact
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: TestResults
        if-no-files-found: ignore 